modLoader="javafml"
loaderVersion="[20,)"
license="Unlicense"
logoFile="pack.png"
logoBlur=false

[[mods]]
modId="ponyorigins"
displayName="Pony Origins"
version="1.4.0-b1"
description='''
Origins Replacement Mod, designed to compliment Mine Little Pony.
'''
[[dependencies.ponyorigins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.0,1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.ponyorigins]]
    modId="origins"
    mandatory=true
    versionRange="[0.1.0,)"
    ordering="NONE"
    side="BOTH"
